# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Part 1 - Data Preprocessing

### Importing the dataset

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [4]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [6]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [8]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

### Feature Scaling

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [29]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [30]:
ann.add(tf.keras.layers.Dense(units=20, activation='relu'))

### Adding the second hidden layer

In [31]:
ann.add(tf.keras.layers.Dense(units=20, activation='relu'))
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))

In [32]:
ann.add(tf.keras.layers.Dense(units=10, activation='relu'))

### Adding the output layer

In [33]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [34]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [35]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5161 - accuracy: 0.7763
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4400 - accuracy: 0.8011
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4206 - accuracy: 0.8149
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4037 - accuracy: 0.8267
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3794 - accuracy: 0.8397
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3593 - accuracy: 0.8528
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3500 - accuracy: 0.8565
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3435 - accuracy: 0.8611
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3392 - accuracy: 0.8627
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3366 - accura

250/250 [==============================] - 0s 2ms/step - loss: 0.2889 - accuracy: 0.8840
Epoch 82/100
250/250 [==============================] - 0s 2ms/step - loss: 0.2895 - accuracy: 0.8834
Epoch 83/100
250/250 [==============================] - 0s 2ms/step - loss: 0.2876 - accuracy: 0.8815
Epoch 84/100
250/250 [==============================] - 0s 2ms/step - loss: 0.2891 - accuracy: 0.8816
Epoch 85/100
250/250 [==============================] - 1s 2ms/step - loss: 0.2871 - accuracy: 0.8829
Epoch 86/100
250/250 [==============================] - 1s 2ms/step - loss: 0.2861 - accuracy: 0.8820
Epoch 87/100
250/250 [==============================] - 0s 2ms/step - loss: 0.2869 - accuracy: 0.8817
Epoch 88/100
250/250 [==============================] - 1s 2ms/step - loss: 0.2875 - accuracy: 0.8836
Epoch 89/100
250/250 [==============================] - 1s 2ms/step - loss: 0.2863 - accuracy: 0.8831
Epoch 90/100
250/250 [==============================] - 1s 2ms/step - loss: 0.2846 - accuracy: 

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [ ]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [36]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1489  106]
 [ 186  219]]


0.854

In [45]:
for var in range(10):
    print(var+1)
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.05, random_state = 0)
    sc = StandardScaler()
    X_train = sc.fit_transform(X_train)
    X_test = sc.transform(X_test)
    ann = tf.keras.models.Sequential()
    aux = var+1
    for i in range(aux):
        ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
    ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
    ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    ann.fit(X_train, y_train, batch_size = 30, epochs = 100, verbose=0)
    y_pred = ann.predict(X_test)
    y_pred = (y_pred > 0.5)
    print(accuracy_score(y_test, y_pred))

1
0.878
2
0.878
3
0.874
4
0.87
5
0.876
6
0.872
7
0.802
8
0.864
9
0.866
10
0.802


In [ ]:
sample_train = 5
layers = 3
nodes = 6
batch_size = 30